/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.mavenproject4;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Patrick L Teixeira
 */
public class Dashboard extends javax.swing.JFrame {

    Dados cpu = new Dados();
    Dados disco = new Dados();
    Double vlrBarDisco = 0.0;
    Dados mem = new Dados();
    
    Double num = 0.0;
    
    Integer click = 0;
    
    void numClick(){
        click++;
    }
       
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prgCpu = new javax.swing.JProgressBar();
        prgDisco = new javax.swing.JProgressBar();
        prgMemoria = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMinCpu = new javax.swing.JLabel();
        lblMedCpu = new javax.swing.JLabel();
        lblMaxCpu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMedDisco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblMaxDisco = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMinMem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMedMem = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMaxMem = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(649, 479));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard - Máquina");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 31, -1, -1));

        prgCpu.setMaximum(30);
        prgCpu.setPreferredSize(new java.awt.Dimension(146, 25));
        getContentPane().add(prgCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 120, 396, -1));

        prgDisco.setPreferredSize(new java.awt.Dimension(146, 25));
        getContentPane().add(prgDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 209, 396, -1));

        prgMemoria.setMaximum(40);
        prgMemoria.setPreferredSize(new java.awt.Dimension(146, 25));
        getContentPane().add(prgMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 300, 396, -1));

        jLabel2.setText("Max:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel3.setText("Min:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 98, -1, -1));

        jLabel4.setText("Media: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 98, -1, -1));

        lblMinCpu.setText("0");
        getContentPane().add(lblMinCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 98, -1, -1));

        lblMedCpu.setText("0");
        getContentPane().add(lblMedCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 98, -1, -1));

        lblMaxCpu.setText("0");
        getContentPane().add(lblMaxCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel5.setText("Min:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 187, -1, -1));

        lblMinDisco.setText("0");
        getContentPane().add(lblMinDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 187, -1, -1));

        jLabel6.setText("Media: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 187, -1, -1));

        lblMedDisco.setText("0");
        getContentPane().add(lblMedDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 187, -1, -1));

        jLabel7.setText("Max:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        lblMaxDisco.setText("0");
        getContentPane().add(lblMaxDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel8.setText("Min:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 278, -1, -1));

        lblMinMem.setText("0");
        getContentPane().add(lblMinMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 278, -1, -1));

        jLabel9.setText("Media: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 278, -1, -1));

        lblMedMem.setText("0");
        getContentPane().add(lblMedMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 278, -1, -1));

        jLabel10.setText("Max:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        lblMaxMem.setText("0");
        getContentPane().add(lblMaxMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        btnGerar.setText("Gerar Dados");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 383, -1, -1));

        setBounds(0, 0, 665, 518);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        // TODO add your handling code here
        numClick();
        
        prgCpu.setStringPainted(true);
        prgDisco.setStringPainted(true);
        prgMemoria.setStringPainted(true);
        
        
        prgDisco.setString("Disco");
        prgMemoria.setString("Memoria");
        
        cpu.gerar(3, click);
        prgCpu.setValue(cpu.vlr.intValue());
        lblMinCpu.setText(String.format("%.2f", cpu.min));
        lblMedCpu.setText(String.format("%.2f", cpu.med));
        lblMaxCpu.setText(String.format("%.2f", cpu.max));
        prgCpu.setString(String.format("CPU: %.2f", cpu.vlr / 10));
        
        disco.gerar(100, click);
        vlrBarDisco = disco.vlr / 10;
        prgDisco.setValue(vlrBarDisco.intValue());
        lblMinDisco.setText(String.format("%.2f", disco.min));
        lblMedDisco.setText(String.format("%.2f", disco.med));
        lblMaxDisco.setText(String.format("%.2f", disco.max));
        prgDisco.setString(String.format("Disco: %.0f", disco.vlr));
        
        mem.gerar(4, click);
        prgMemoria.setValue(mem.vlr.intValue());
        lblMinMem.setText(String.format("%.2f", mem.min));
        lblMedMem.setText(String.format("%.2f", mem.med));
        lblMaxMem.setText(String.format("%.2f", mem.max));
        prgMemoria.setString(String.format("Memória: %.2f", mem.vlr / 10));
        
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMaxCpu;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxMem;
    private javax.swing.JLabel lblMedCpu;
    private javax.swing.JLabel lblMedDisco;
    private javax.swing.JLabel lblMedMem;
    private javax.swing.JLabel lblMinCpu;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinMem;
    private javax.swing.JProgressBar prgCpu;
    private javax.swing.JProgressBar prgDisco;
    private javax.swing.JProgressBar prgMemoria;
    // End of variables declaration//GEN-END:variables
}
